name: Continuous Integration (CI)

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: agrotech_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MYSQL_HOST: mysql

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache de dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Descargar dependencias
        run: mvn dependency:go-offline

      - name: Esperar a que MySQL esté listo
        run: |
          while ! mysqladmin ping -h"mysql" -P"3306" -uroot -p"12345678" --protocol=tcp --silent; do
            sleep 1
            echo "Esperando a MySQL..."
          done

      - name: Build y Tests
        run: mvn -B clean verify