name: Continuous Integration (CI)

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: agrotech_test
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Checkout MySQL
        run: mysql -h 127.0.0.1 --port 3306 -u root -p12345678 -e 'CREATE DATABASE IF NOT EXISTS agrotech_test;'

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache de dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Descargar dependencias
        run: mvn dependency:go-offline

      - name: Build y Tests
        run: mvn -B clean verify