name: Continuous Integration (CI)

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MYSQL_USER: ci_user

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Configurar MySQL con base de datos y usuario
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql

          # Crear base de datos y usuario con permisos
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS agrotech_test;"
          sudo mysql -e "CREATE USER IF NOT EXISTS 'ci_user'@'localhost' IDENTIFIED BY '12345678';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON agrotech_test.* TO 'ci_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

          # Verificar conexión
          mysql -uci_user -p12345678 -e "SHOW DATABASES;"

      - name: Cache de dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Descargar dependencias
        run: mvn dependency:go-offline

      - name: Build y Tests
        run: mvn -B clean verify